FROM apache/airflow:3.2.1

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl postgresql-client \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir "apache-airflow==${AIRFLOW_VERSION}" -r /tmp/requirements.txt